### ISSUE TITLE
VincentyInvRevAzimuth gives the same result as VincentyInvFwdAzimuth

### ISSUE THREAD

**Issue by louisrousseau** [tdjastrzebski/VincentyExcel#1]
Workaround: swap the coordinates and use forward azimuth

**Comment by tdjastrzebski** [comment]
Hi, could you provide an example please?

**Comment by tdjastrzebski** [comment]
I was unable to replicate the issue. The largest differences I found between the two methods (swapping coordinates) was 5.7E-14.
