### ISSUE TITLE
VincentyInvFwdAzimuth: Check For Equator Straight line (90/270)

### ISSUE THREAD

**Issue by Azimu** [tdjastrzebski/VincentyExcel#2]
For the VincentyInvFwdAzimuth function, could you do some check for both Lat1 and Lat2 being ZERO (the Equator)?  There is an overflow error currently with this function.   Maybe type something like If lat1+lat2 = 0 then If lon1>lon2 Then VincentyInvFwdAzimuth = 270 else it's 90.

**Comment by tdjastrzebski** [comment]
Thanks, I will look into it.

**Comment by tdjastrzebski** [comment]
Please check it out. Azimuth calculations on the Equator should be corrected.
There is one issue I have noticed: VincentyInvDistance function is unble to calculate distance if lon2=lon1+180 (azimuth is nondeterministic).
