### ISSUE TITLE
Browser Pane?

### ISSUE THREAD

**Issue by swkong** [tdjastrzebski/VincentyExcel#4]
I am probably using an older version of Excel (2003).
I don't understand your instruction

Next, in the browser panel right-click on VBA Project (your file name), select Import File and choose downloaded Vincenty.bas module.

I seem to have it working sort of but would like to install the module properly.  It is a great tool.  Im using it to calculate the locations of local wild fires.

**Comment by swkong** [comment]
Is there another way to implement this in excel 2003?

**Comment by tdjastrzebski** [comment]
I am glad to hear it is of good use :)
