### ISSUE TITLE
The VincentyInvDistance function has trouble converging when the distance is very small

### ISSUE THREAD

**Issue by pkolinko** [tdjastrzebski/VincentyExcel#5]
Hello - thank you for the really great work translating the Vincenty algorithm into Excel VBA. 
The VincentyInvDistance function works great when the total position error is > 1 meter, but below 1 meter we found it has trouble converging sometimes, especially if < 0.2 meter error between (lat1, long1, lat2, long 2). 
Would be good for someone with professional math / compsci background to figure out the proper computation algorithm and code,

**Comment by tdjastrzebski** [comment]
Hello @pkolinko, this Excel add-in only adopts implementation done by @chrisveness.
If the problem/limitation exists in the original JavaScript implementation (https://github.com/chrisveness/geodesy), it also exists here. Please test it and, if results are what I expect, notify Chris.

**Comment by chrisveness** [comment]
I can confirm that if the distance between the two points is less than around 100mm, the check for co-incident (or antipodal) points, which tests for [sin²σ < ε](https://github.com/chrisveness/geodesy/blob/49a500cb8857e6c274b6449067464c1cd89686a8/latlon-ellipsoidal-vincenty.js#L288), fails (σ is the angular distance P₁–P₂, [ε](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/EPSILON) is the machine precision).

To my recollection, Vincenty didn't delve too deeply into numerical analysis of floating point arithmetic (indeed I don't know if Fortran used IEEE 754 floating point arithmetic).

The check for co-incident/antipodal points was empirically determined – I shall see if the test can be refined to improve results below 100mm.

**Comment by chrisveness** [comment]
My test for coincident points was incorrect: following through the maths, a value of ε for sin²σ corresponds to around 95mm between points, whereas Vincenty claims sub-mm accuracy; using TV's preferred value of 1e-12 radians (c. 0.006mm) for 'negligible', a check for sin²σ < 1e-24 gives good results down to 2mm distance between points.

I have [corrected](https://github.com/chrisveness/geodesy/commit/26c73cb9) my library to use a test [sin²σ < 1e-24](https://github.com/chrisveness/geodesy/blob/8f4ef33d/latlon-ellipsoidal-vincenty.js#L288).

**Comment by tdjastrzebski** [comment]
@pkolinko I have just pushed changes, please check if the problem is fixed.
