### ISSUE TITLE
VincentyDirLat error "Expression too complex" (Excel 32-bit, Windows 10)

### ISSUE THREAD

**Issue by michaelwilsonnz** [tdjastrzebski/VincentyExcel#6]
Hi, firstly thanks for this great library! I have an issue where I get a #VALUE error when using the VincentyDirLat function. On running in the VBA Immediate window I get "Run-time error '16': Expression too complex". I get this when running the following example:
VincentyDirLat(-37.12345,174.12345,1.0,10.0) Running on Microsoft Excel for Office 365 MSO (16.0.11929.20436) 32-bit on Windows 10.
Any ideas? 
Kind Regards from Aotearoa New Zealand, 
Michael.

**Comment by tdjastrzebski** [comment]
@michaelwilsonnz, thank you.
Excel VBA expressions have certain yet totally undocumented complexity limits. I have a feeling that with every new Excel version this limit gets lower.  
I think MS tries to gently discourage us from using VBA and prepare us for transition to Excel online.  
I will test with Excel 365 within days.

**Comment by michaelwilsonnz** [comment]
Thank you. Yes it seems the unwieldly power that is VBA is slowly getting diluted.. Don't spend too much time on this, if it doesn't work and its not an easy fix I will try another option.
In saying that, if you want some help to do testing, please feel free to call on me. Regards.

**Comment by tdjastrzebski** [comment]
@michaelwilsonnz Please verify the issue is fixed and let me know.

**Comment by michaelwilsonnz** [comment]
@tdjastrzebski thank you yes this works for me now. Much appreciated, thank you!
